# This file was generated by GoReleaser. DO NOT EDIT.
# Maintainer: darkprince558 <darkprince558@users.noreply.github.com>

pkgname='jend-bin'
pkgver=2.7.0
pkgrel=1
pkgdesc='JEND: Just Enough Network Drop - Modern, secure, P2P file transfer.'
url='https://github.com/darkprince558/jend'
arch=('aarch64' 'x86_64')
license=('MIT')
provides=('jend')
conflicts=('jend')

source_aarch64=("${pkgname}_${pkgver}_aarch64.tar.gz::https://github.com/darkprince558/JEND/releases/download/v${pkgver}/jend_Linux_arm64.tar.gz")
sha256sums_aarch64=('37dc95ecd4b4a7c4bb0cf3154c9c126759801fc5c32035cedcfc79788d955ff1')

source_x86_64=("${pkgname}_${pkgver}_x86_64.tar.gz::https://github.com/darkprince558/JEND/releases/download/v${pkgver}/jend_Linux_x86_64.tar.gz")
sha256sums_x86_64=('9e4d7b866c99d8f3c7ede78ac3d96d411ffe4fffc2bf3726bb699660c019ded2')

package() {
  # bin
  install -Dm755 "./jend" "${pkgdir}/usr/bin/jend"
}
