# This file was generated by GoReleaser. DO NOT EDIT.
# Maintainer: darkprince558 <darkprince558@users.noreply.github.com>

pkgname='jend-bin'
pkgver=2.8.1
pkgrel=1
pkgdesc='JEND - Modern, secure, P2P file transfer.'
url='https://github.com/darkprince558/jend'
arch=('aarch64' 'x86_64')
license=('MIT')
provides=('jend')
conflicts=('jend')

source_aarch64=("${pkgname}_${pkgver}_aarch64.tar.gz::https://github.com/darkprince558/JEND/releases/download/v${pkgver}/jend_Linux_arm64.tar.gz")
sha256sums_aarch64=('e9a102b559fcce6cc58f2b6d0f8594ec77a5fb36fcb79f92cf2d78a9b7eb63ba')

source_x86_64=("${pkgname}_${pkgver}_x86_64.tar.gz::https://github.com/darkprince558/JEND/releases/download/v${pkgver}/jend_Linux_x86_64.tar.gz")
sha256sums_x86_64=('fdf7021e3f120ccb8d6cb90f21c7983ed01c648ebd098b17c3846a1f297b755f')

package() {
  # bin
  install -Dm755 "./jend" "${pkgdir}/usr/bin/jend"
}
