# This file was generated by GoReleaser. DO NOT EDIT.
# Maintainer: darkprince558 <darkprince558@users.noreply.github.com>

pkgname='jend-bin'
pkgver=2.4.0
pkgrel=1
pkgdesc='JEND: Just Enough Network Drop - Modern, secure, P2P file transfer.'
url='https://github.com/darkprince558/jend'
arch=('aarch64' 'x86_64')
license=('MIT')
provides=('jend')
conflicts=('jend')

source_aarch64=("${pkgname}_${pkgver}_aarch64.tar.gz::https://github.com/darkprince558/JEND/releases/download/v${pkgver}/jend_Linux_arm64.tar.gz")
sha256sums_aarch64=('643caef49e455225dd42a2cc45e82d5b75f3c858f7ae1e591823e4a8dedb1575')

source_x86_64=("${pkgname}_${pkgver}_x86_64.tar.gz::https://github.com/darkprince558/JEND/releases/download/v${pkgver}/jend_Linux_x86_64.tar.gz")
sha256sums_x86_64=('00e31f110772d761730bb89276f6b9ca1132a8da85d85180bfd8615533e31870')

package() {
  # bin
  install -Dm755 "./jend" "${pkgdir}/usr/bin/jend"
}
